var annotated_dup =
[
    [ "gts", null, [
      [ "analysis", null, [
        [ "ConcurrentLoggerEvent", "structgts_1_1analysis_1_1_concurrent_logger_event.html", "structgts_1_1analysis_1_1_concurrent_logger_event" ],
        [ "ConcurrentLogger", "classgts_1_1analysis_1_1_concurrent_logger.html", "classgts_1_1analysis_1_1_concurrent_logger" ],
        [ "WorkerPoolCounters", "structgts_1_1analysis_1_1_worker_pool_counters.html", "structgts_1_1analysis_1_1_worker_pool_counters" ],
        [ "MicroSchedulerCounters", "structgts_1_1analysis_1_1_micro_scheduler_counters.html", "structgts_1_1analysis_1_1_micro_scheduler_counters" ],
        [ "Counter", "classgts_1_1analysis_1_1_counter.html", "classgts_1_1analysis_1_1_counter" ],
        [ "TraceConcurrentLogger", "classgts_1_1analysis_1_1_trace_concurrent_logger.html", null ],
        [ "IttNotify", "classgts_1_1analysis_1_1_itt_notify.html", "classgts_1_1analysis_1_1_itt_notify" ],
        [ "TracyState", "classgts_1_1analysis_1_1_tracy_state.html", "classgts_1_1analysis_1_1_tracy_state" ]
      ] ],
      [ "internal", null, [
        [ "BlockAllocator", "classgts_1_1internal_1_1_block_allocator.html", "classgts_1_1internal_1_1_block_allocator" ],
        [ "GuardBase", "classgts_1_1internal_1_1_guard_base.html", "classgts_1_1internal_1_1_guard_base" ],
        [ "ParallelSubVector", "classgts_1_1internal_1_1_parallel_sub_vector.html", "classgts_1_1internal_1_1_parallel_sub_vector" ],
        [ "TicketQueueMPMC", "classgts_1_1internal_1_1_ticket_queue_m_p_m_c.html", "classgts_1_1internal_1_1_ticket_queue_m_p_m_c" ],
        [ "TicketQueueMPSC", "classgts_1_1internal_1_1_ticket_queue_m_p_s_c.html", "classgts_1_1internal_1_1_ticket_queue_m_p_s_c" ],
        [ "TicketQueueSPMC", "classgts_1_1internal_1_1_ticket_queue_s_p_m_c.html", "classgts_1_1internal_1_1_ticket_queue_s_p_m_c" ]
      ] ],
      [ "AlignedAllocator", "classgts_1_1_aligned_allocator.html", "classgts_1_1_aligned_allocator" ],
      [ "IntrusiveDList", "classgts_1_1_intrusive_d_list.html", "classgts_1_1_intrusive_d_list" ],
      [ "OsHeapAllocator", "classgts_1_1_os_heap_allocator.html", "classgts_1_1_os_heap_allocator" ],
      [ "FreeListNode", "structgts_1_1_free_list_node.html", "structgts_1_1_free_list_node" ],
      [ "MemoryStore", "structgts_1_1_memory_store.html", "structgts_1_1_memory_store" ],
      [ "BinnedAllocator", "classgts_1_1_binned_allocator.html", "classgts_1_1_binned_allocator" ],
      [ "ReadGuard", "classgts_1_1_read_guard.html", "classgts_1_1_read_guard" ],
      [ "WriteGuard", "classgts_1_1_write_guard.html", "classgts_1_1_write_guard" ],
      [ "KeyValue", "structgts_1_1_key_value.html", "structgts_1_1_key_value" ],
      [ "ParallelHashTable", "classgts_1_1_parallel_hash_table.html", "classgts_1_1_parallel_hash_table" ],
      [ "ParallelVector", "classgts_1_1_parallel_vector.html", "classgts_1_1_parallel_vector" ],
      [ "QueueMPMC", "classgts_1_1_queue_m_p_m_c.html", "classgts_1_1_queue_m_p_m_c" ],
      [ "QueueMPSC", "classgts_1_1_queue_m_p_s_c.html", "classgts_1_1_queue_m_p_s_c" ],
      [ "QueueSPMC", "classgts_1_1_queue_s_p_m_c.html", "classgts_1_1_queue_s_p_m_c" ],
      [ "QueueSPSC", "classgts_1_1_queue_s_p_s_c.html", "classgts_1_1_queue_s_p_s_c" ],
      [ "RingDeque", "classgts_1_1_ring_deque.html", "classgts_1_1_ring_deque" ],
      [ "Vector", "classgts_1_1_vector.html", "classgts_1_1_vector" ],
      [ "MicroScheduler_ComputeResource", "classgts_1_1_micro_scheduler___compute_resource.html", "classgts_1_1_micro_scheduler___compute_resource" ],
      [ "MicroScheduler_Task", "classgts_1_1_micro_scheduler___task.html", "classgts_1_1_micro_scheduler___task" ],
      [ "MicroScheduler_Workload", "classgts_1_1_micro_scheduler___workload.html", "classgts_1_1_micro_scheduler___workload" ],
      [ "MicroSchedulerLambda_Workload", "classgts_1_1_micro_scheduler_lambda___workload.html", "classgts_1_1_micro_scheduler_lambda___workload" ],
      [ "ComputeResource", "classgts_1_1_compute_resource.html", "classgts_1_1_compute_resource" ],
      [ "DagUtils", "structgts_1_1_dag_utils.html", "structgts_1_1_dag_utils" ],
      [ "MacroScheduler", "classgts_1_1_macro_scheduler.html", "classgts_1_1_macro_scheduler" ],
      [ "MacroSchedulerDesc", "structgts_1_1_macro_scheduler_desc.html", "structgts_1_1_macro_scheduler_desc" ],
      [ "WorkloadContext", "structgts_1_1_workload_context.html", "structgts_1_1_workload_context" ],
      [ "WorkloadType", "structgts_1_1_workload_type.html", "structgts_1_1_workload_type" ],
      [ "ComputeResourceType", "structgts_1_1_compute_resource_type.html", "structgts_1_1_compute_resource_type" ],
      [ "Node", "classgts_1_1_node.html", "classgts_1_1_node" ],
      [ "Schedule", "classgts_1_1_schedule.html", "classgts_1_1_schedule" ],
      [ "CriticalNode_MacroScheduler", "classgts_1_1_critical_node___macro_scheduler.html", "classgts_1_1_critical_node___macro_scheduler" ],
      [ "CriticalNode_Schedule", "classgts_1_1_critical_node___schedule.html", "classgts_1_1_critical_node___schedule" ],
      [ "CentralQueue_MacroScheduler", "classgts_1_1_central_queue___macro_scheduler.html", "classgts_1_1_central_queue___macro_scheduler" ],
      [ "CentralQueue_Schedule", "classgts_1_1_central_queue___schedule.html", "classgts_1_1_central_queue___schedule" ],
      [ "Workload", "classgts_1_1_workload.html", "classgts_1_1_workload" ],
      [ "MicroScheduler", "classgts_1_1_micro_scheduler.html", "classgts_1_1_micro_scheduler" ],
      [ "TaskContext", "structgts_1_1_task_context.html", "structgts_1_1_task_context" ],
      [ "WorkerThreadDesc", "structgts_1_1_worker_thread_desc.html", "structgts_1_1_worker_thread_desc" ],
      [ "WorkerPoolVisitor", "structgts_1_1_worker_pool_visitor.html", "structgts_1_1_worker_pool_visitor" ],
      [ "WorkerPoolDesc", "structgts_1_1_worker_pool_desc.html", "structgts_1_1_worker_pool_desc" ],
      [ "MicroSchedulerDesc", "structgts_1_1_micro_scheduler_desc.html", "structgts_1_1_micro_scheduler_desc" ],
      [ "KdRange2d", "classgts_1_1_kd_range2d.html", "classgts_1_1_kd_range2d" ],
      [ "KdRange3d", "classgts_1_1_kd_range3d.html", "classgts_1_1_kd_range3d" ],
      [ "OctRange", "classgts_1_1_oct_range.html", "classgts_1_1_oct_range" ],
      [ "ParallelFor", "classgts_1_1_parallel_for.html", "classgts_1_1_parallel_for" ],
      [ "ParallelReduce", "classgts_1_1_parallel_reduce.html", "classgts_1_1_parallel_reduce" ],
      [ "DependencyArray", "classgts_1_1_dependency_array.html", null ],
      [ "DependencyArray< TValRange, TDepRange, 2 >", "classgts_1_1_dependency_array_3_01_t_val_range_00_01_t_dep_range_00_012_01_4.html", "classgts_1_1_dependency_array_3_01_t_val_range_00_01_t_dep_range_00_012_01_4" ],
      [ "LaunchTask", "structgts_1_1_launch_task.html", null ],
      [ "LaunchTask< 2 >", "structgts_1_1_launch_task_3_012_01_4.html", null ],
      [ "LaunchTask< 3 >", "structgts_1_1_launch_task_3_013_01_4.html", null ],
      [ "ParallelWavefront", "classgts_1_1_parallel_wavefront.html", "classgts_1_1_parallel_wavefront" ],
      [ "SimplePartitioner", "classgts_1_1_simple_partitioner.html", "classgts_1_1_simple_partitioner" ],
      [ "StaticPartitioner", "classgts_1_1_static_partitioner.html", "classgts_1_1_static_partitioner" ],
      [ "QuadRange", "classgts_1_1_quad_range.html", "classgts_1_1_quad_range" ],
      [ "Range1d", "classgts_1_1_range1d.html", "classgts_1_1_range1d" ],
      [ "SplitResult", "structgts_1_1_split_result.html", null ],
      [ "SplitResult< TRange, MaxSplits, 1 >", "structgts_1_1_split_result_3_01_t_range_00_01_max_splits_00_011_01_4.html", "structgts_1_1_split_result_3_01_t_range_00_01_max_splits_00_011_01_4" ],
      [ "SplitResult< TRange, MaxSplits, 2 >", "structgts_1_1_split_result_3_01_t_range_00_01_max_splits_00_012_01_4.html", "structgts_1_1_split_result_3_01_t_range_00_01_max_splits_00_012_01_4" ],
      [ "SplitResult< TRange, MaxSplits, 3 >", "structgts_1_1_split_result_3_01_t_range_00_01_max_splits_00_013_01_4.html", "structgts_1_1_split_result_3_01_t_range_00_01_max_splits_00_013_01_4" ],
      [ "EvenSplitter", "structgts_1_1_even_splitter.html", null ],
      [ "ProportionalSplitter", "structgts_1_1_proportional_splitter.html", "structgts_1_1_proportional_splitter" ],
      [ "Task", "classgts_1_1_task.html", "classgts_1_1_task" ],
      [ "CStyleTask", "classgts_1_1_c_style_task.html", "classgts_1_1_c_style_task" ],
      [ "LambdaTaskWrapper", "classgts_1_1_lambda_task_wrapper.html", "classgts_1_1_lambda_task_wrapper" ],
      [ "EmptyTask", "classgts_1_1_empty_task.html", "classgts_1_1_empty_task" ],
      [ "WorkerPool", "classgts_1_1_worker_pool.html", "classgts_1_1_worker_pool" ],
      [ "AtomicCommon", "structgts_1_1_atomic_common.html", "structgts_1_1_atomic_common" ],
      [ "AtomicArithmetic", "structgts_1_1_atomic_arithmetic.html", "structgts_1_1_atomic_arithmetic" ],
      [ "AtomicPointer", "structgts_1_1_atomic_pointer.html", "structgts_1_1_atomic_pointer" ],
      [ "Atomic", "classgts_1_1_atomic.html", "classgts_1_1_atomic" ],
      [ "Atomic< T * >", "classgts_1_1_atomic_3_01_t_01_5_01_4.html", "classgts_1_1_atomic_3_01_t_01_5_01_4" ],
      [ "Atomic< bool >", "classgts_1_1_atomic_3_01bool_01_4.html", "classgts_1_1_atomic_3_01bool_01_4" ],
      [ "InstructionSet", "classgts_1_1_instruction_set.html", null ],
      [ "CpuCoreInfo", "structgts_1_1_cpu_core_info.html", "structgts_1_1_cpu_core_info" ],
      [ "SocketInfo", "structgts_1_1_socket_info.html", "structgts_1_1_socket_info" ],
      [ "NumaNodeInfo", "structgts_1_1_numa_node_info.html", "structgts_1_1_numa_node_info" ],
      [ "ProcessorGroupInfo", "structgts_1_1_processor_group_info.html", "structgts_1_1_processor_group_info" ],
      [ "SystemTopology", "structgts_1_1_system_topology.html", "structgts_1_1_system_topology" ],
      [ "Thread", "classgts_1_1_thread.html", "classgts_1_1_thread" ],
      [ "ThisThread", "structgts_1_1_this_thread.html", null ],
      [ "BinarySemaphore", "classgts_1_1_binary_semaphore.html", "classgts_1_1_binary_semaphore" ],
      [ "numericLimits", "structgts_1_1numeric_limits.html", null ],
      [ "numericLimits< uint32_t >", "structgts_1_1numeric_limits_3_01uint32__t_01_4.html", null ],
      [ "numericLimits< uint64_t >", "structgts_1_1numeric_limits_3_01uint64__t_01_4.html", null ],
      [ "numericLimits< int32_t >", "structgts_1_1numeric_limits_3_01int32__t_01_4.html", null ],
      [ "numericLimits< int64_t >", "structgts_1_1numeric_limits_3_01int64__t_01_4.html", null ],
      [ "IsPow2", "structgts_1_1_is_pow2.html", null ],
      [ "OwnedId", "classgts_1_1_owned_id.html", "classgts_1_1_owned_id" ],
      [ "MurmurHash", "structgts_1_1_murmur_hash.html", "structgts_1_1_murmur_hash" ],
      [ "MurmurHash< float >", "structgts_1_1_murmur_hash_3_01float_01_4.html", "structgts_1_1_murmur_hash_3_01float_01_4" ],
      [ "MurmurHash< double >", "structgts_1_1_murmur_hash_3_01double_01_4.html", "structgts_1_1_murmur_hash_3_01double_01_4" ],
      [ "MurmurHash< char * >", "structgts_1_1_murmur_hash_3_01char_01_5_01_4.html", "structgts_1_1_murmur_hash_3_01char_01_5_01_4" ],
      [ "MurmurHash< TKey * >", "structgts_1_1_murmur_hash_3_01_t_key_01_5_01_4.html", "structgts_1_1_murmur_hash_3_01_t_key_01_5_01_4" ],
      [ "Backoff", "classgts_1_1_backoff.html", "classgts_1_1_backoff" ],
      [ "LockShared", "structgts_1_1_lock_shared.html", "structgts_1_1_lock_shared" ],
      [ "Lock", "structgts_1_1_lock.html", "structgts_1_1_lock" ],
      [ "UnfairSpinMutex", "classgts_1_1_unfair_spin_mutex.html", "classgts_1_1_unfair_spin_mutex" ],
      [ "FairSpinMutex", "classgts_1_1_fair_spin_mutex.html", "classgts_1_1_fair_spin_mutex" ],
      [ "UnfairSharedSpinMutex", "classgts_1_1_unfair_shared_spin_mutex.html", "classgts_1_1_unfair_shared_spin_mutex" ]
    ] ],
    [ "gts_examples", null, [
      [ "BasicTask", "structgts__examples_1_1_basic_task.html", "structgts__examples_1_1_basic_task" ],
      [ "ParallelFibTask1", "structgts__examples_1_1_parallel_fib_task1.html", "structgts__examples_1_1_parallel_fib_task1" ],
      [ "ParallelFibContinuationTask", "structgts__examples_1_1_parallel_fib_continuation_task.html", "structgts__examples_1_1_parallel_fib_continuation_task" ],
      [ "ParallelFibTask2", "structgts__examples_1_1_parallel_fib_task2.html", "structgts__examples_1_1_parallel_fib_task2" ],
      [ "ParallelFibContinuationTask3", "structgts__examples_1_1_parallel_fib_continuation_task3.html", "structgts__examples_1_1_parallel_fib_continuation_task3" ],
      [ "ParallelFibTask3", "structgts__examples_1_1_parallel_fib_task3.html", "structgts__examples_1_1_parallel_fib_task3" ],
      [ "ParallelFibContinuationTask4", "structgts__examples_1_1_parallel_fib_continuation_task4.html", "structgts__examples_1_1_parallel_fib_continuation_task4" ],
      [ "ParallelFibTask4", "structgts__examples_1_1_parallel_fib_task4.html", "structgts__examples_1_1_parallel_fib_task4" ],
      [ "GridSumTask", "classgts__examples_1_1_grid_sum_task.html", "classgts__examples_1_1_grid_sum_task" ],
      [ "GridCell", "structgts__examples_1_1_grid_cell.html", "structgts__examples_1_1_grid_cell" ],
      [ "BadParallelFor", "classgts__examples_1_1_bad_parallel_for.html", "classgts__examples_1_1_bad_parallel_for" ]
    ] ],
    [ "AdaptivePartitioner", "class_adaptive_partitioner.html", "class_adaptive_partitioner" ]
];